function help() {
    console.log('\n  Usage:')
    console.log('\n node app.js <options>')
    console.log('\n   Note: options can include one or more of the following:\n')
    console.log('\t --help \t\t\t\t display this help information')
    console.log('\t --h \t\t\t\t\t display this help information')
    console.log('\t --fileRoot=\'../StdCosting\' \t\t specify where to locate source files')
    console.log('\t\t\t\t\t\t\t default=\'../../StdCosting\'')
    console.log('\t --hierarchySource=\'project.xlsx\' \t specify name of source files')
    console.log('\t\t\t\t\t\t\t default=\'elbert.xlsx\'')
    console.log('\t --hierarchyTab=\'Hierarchy Index\' \t  specify tab name of hierarchy index ')
    console.log('\t\t\t\t\t\t\t default=\'Hierarchy Index\'')
    console.log('\t --manHrsPerWk=30 \t\t\t hrs per week (not incl. non-productive overhead)')
    console.log('\t\t\t\t\t\t\t default=36')
    console.log('\t --fileRoot=\'../StdCosting\' \t\t specify where to locate source files')
    console.log('\t\t\t\t\t\t\t default=\'../../ StdCosting \'')
    console.log('\t --options \t\t\t\t display the command line arguments')
    console.log('\t --import \t\t\t\t perform an import from source files')
    console.log('\t --display \t\t\t\t display report results')
    // console.log()
    console.log('\t\t Note: display options can include one of the following:')
    console.log('\t\t --show \t\t\t display PD and ID totals')
    console.log('\t\t --show=TDxxxMilestones \t display TD Milestone info')
    console.log('\t\t --show=IDxMilestones \t display ID Milestone info')
    console.log('\t\t --show=PDMilestones \t display PD Milestone info')
    console.log('\t\t --show=TDxxxSpecificTotal xxx is replaced with TD number')
    console.log('\t\t --show=IDxSpecificTotal \t x is replaced with ID number')
    console.log('\t\t --show=PDSpecificTotal \t display PD Specific Total info')
    console.log('\t\t --show=TDxxx \t\t xxx is replaced with TD number')
    console.log('\t\t --show=IDx \t\t x is replaced with ID number')
    console.log('\t\t --show=PD \t\t display PD Total info')
    console.log('\t\t --show=PDDetail \t\t display PDDetail with ID details info')
    console.log('\t\t --show=All \t\t display PD Total hierarchy info')
    console.log('\t\t --show=AllMilestones \t display PD Total with Milestones')
    console.log()
    console.log('\n Examples:')
    console.log('\t node app.js help')
    console.log('\t node app.js --help')
    console.log('\t node app.js --h')
    console.log('\t node app.js --fileRoot=\'../../StdCosting\' --import --show=TD101')
    console.log('\t node app.js --hierarchyTab=\'Hierarchy 1\' --import --display --show=TD101')
    console.log('\t node app.js --hierarchyTab=\'Hierarchy Zero\' --import --display --show')
    console.log('\t node app.js --import --display --show')
    console.log('\t node app.js --import --display --show=ID1')
    console.log('\t node app.js --display --show=ID1')
    console.log('\t node app.js --display --show')
    console.log('\t node app.js --display --show=All')
    process.exit(1)
}

module.exports.help = help